services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    restart: unless-stopped
    networks:
      - app-network
  
  nginx:
    container_name: nginx    
    image: nginx:stable-alpine3.21-perl
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - web-root:/var/www/certbot
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - dhparam:/etc/ssl/certs
    depends_on:
      - frontend
    networks:
      - app-network

  certbot:
    container_name: certbot
    image: certbot/certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/certbot
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/www/certbot --email sekosmetics@gmail.com --agree-tos --no-eff-email --staging -d staging.com

networks:
  app-network:
    driver: bridge

volumes:
  web-root:
  certbot-etc:
  certbot-var:
  dhparam: